{
 "title": "Catalyst_2960_dashboard (author: dattrangia)",
 "description": "Cisco",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"cisco\", device_source=\"<SWITCH_IP>\", latitude=\"<YOUR_LATITUDE>\", longitude=\"<YOUR_LONGITUDE>\"}"
    },
    {
     "direction": "backward",
     "expr": "{job=\"ai-report\", latitude=\"<YOUR_LATITUDE>\", longitude=\"<YOUR_LONGITUDE>\"}"
    }
   ]
  },
  { "title": "Security Event Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Log",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"cisco\", device_source=\"<SWITCH_IP>\"}"
    }
   ]
  },
  {
   "title": "Sum Log",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(severity_name) (count_over_time({job=\"cisco\", device_source=\"<SWITCH_IP>\"}[24h]))",
     "legendFormat": "{{serverity_name}}"
    }
   ]
  },
  {
   "title": "MIMIR Report",
   "type": "logs",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"ai-report\"} |= ``"
    }
   ]
  },
  { "title": "Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Top 5 Inbound (Download)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(5, rate(ifHCInOctets{job=\"snmp_switch\", instance=\"<SWITCH_IP>\"}[5m]) * 8)",
     "legendFormat": "In - {{ifName}}"
    }
   ]
  },
  {
   "title": "Top 5 Outbound (Upload)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(5, rate(ifHCOutOctets{job=\"snmp_switch\", instance=\"<SWITCH_IP>\"}[5m]) * 8)",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "CPU 5sec Average",
   "type": "timeseries",
   "description": "Cisco CPU 5sec average utilization\n\n**Type:** *gauge*\n\n",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(cpmCPUTotal5secRev{instance=\"<SWITCH_IP>\" })",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Unicast/Multicast/Broadcast",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ifInUcastPkts{job=\"snmp_switch\", instance=\"<SWITCH_IP>\"}[24h]))",
     "legendFormat": "Unicast"
    },
    {
     "expr": "sum(rate(ifInMulticastPkts{job=\"snmp_switch\", instance=\"<SWITCH_IP>\"}[24h]))",
     "legendFormat": "Multicast"
    },
    {
     "expr": "sum(rate(ifInBroadcastPkts{job=\"snmp_switch\", instance=\"<SWITCH_IP>\"}[24h]))",
     "legendFormat": "Broadcast"
    }
   ]
  },
  {
   "title": "Bandwidth Utilization % per Interface",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sort(\r\n  rate(ifHCInOctets{instance=\"<SWITCH_IP>\", ifName=~\"Fa0/.*\"}[5m]) * 8 / ifSpeed * 100\r\n)",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Interface Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 54 },
   "targets": [
    {
     "expr": "rate(ifInErrors{job=\"snmp_switch\", instance=\"<SWITCH_IP>\", ifName=~\"Fa0/([1-9]|1[0-9]|2[0-4])\"}[5m])",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Interface UP/DOWN",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{job=\"snmp_switch\", instance=\"<SWITCH_IP>\", ifName=~\"Fa0/([1-9]|1[0-9]|2[0-4])\"}",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Switch UpTime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"snmp_switch\", instance=\"<SWITCH_IP>\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory % Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ciscoMemoryPoolUsed{instance=\"<SWITCH_IP>\", ciscoMemoryPoolIndex=\"1\"} / (ciscoMemoryPoolUsed{instance=\"<SWITCH_IP>\", ciscoMemoryPoolIndex=\"1\"} + ciscoMemoryPoolFree{instance=\"<SWITCH_IP>\", ciscoMemoryPoolIndex=\"1\"}) * 100",
     "legendFormat": "Processor"
    },
    {
     "expr": "ciscoMemoryPoolUsed{instance=\"<SWITCH_IP>\", ciscoMemoryPoolIndex=\"2\"} / (ciscoMemoryPoolUsed{instance=\"<SWITCH_IP>\", ciscoMemoryPoolIndex=\"2\"} + ciscoMemoryPoolFree{instance=\"<SWITCH_IP>\", ciscoMemoryPoolIndex=\"2\"}) * 100",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "Proccesses ID CPU% (1min)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, cpmProcExtUtil5SecRev{job=\"snmp-switch-cisco\", instance=\"<SWITCH_IP>\"} > 0)",
     "legendFormat": "{{cpmProcessName}} (PID: {{cpmProcessPID}})"
    }
   ]
  }
 ]
}