{
 "title": "Router_2811_dashboard (author: dattrangia)",
 "description": "Cisco",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"cisco\", device_source=\"<ROUTER_IP>\", latitude=\"<YOUR_LATITUDE>\", longitude=\"<YOUR_LONGITUDE>\"}"
    },
    {
     "direction": "backward",
     "expr": "{job=\"ai-report\", latitude=\"<YOUR_LATITUDE>\", longitude=\"<YOUR_LONGITUDE>\"}"
    }
   ]
  },
  { "title": "Security Event Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"cisco\", device_source=\"<ROUTER_IP>\"}"
    }
   ]
  },
  {
   "title": "Sum Log",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(severity_name) (count_over_time({job=\"cisco\", device_source=\"<ROUTER_IP>\"}[24h]))",
     "legendFormat": "{{serverity_name}}"
    }
   ]
  },
  { "title": "Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Top 5 Inbound (Download)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "topk(5, rate(ifHCInOctets{job=\"snmp_switch\", instance=\"<ROUTER_IP>\"}[5m]) * 8)",
     "legendFormat": "In - {{ifName}}"
    }
   ]
  },
  {
   "title": "Top 5 Outbound (Upload)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "topk(5, rate(ifHCOutOctets{job=\"snmp_switch\", instance=\"<ROUTER_IP>\"}[5m]) * 8)",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "CPU 5sec Average",
   "type": "timeseries",
   "description": "Cisco CPU 5sec average utilization\n\n**Type:** *gauge*\n\n",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(cpmCPUTotal5secRev{instance=\"<ROUTER_IP>\" })",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Unicast/Multicast/Broadcast",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ifInUcastPkts{job=\"snmp_switch\", instance=\"<ROUTER_IP>\"}[5m]))",
     "legendFormat": "Unicast"
    },
    {
     "expr": "sum(rate(ifInMulticastPkts{job=\"snmp_switch\", instance=\"<ROUTER_IP>\"}[5m]))",
     "legendFormat": "Multicast"
    },
    {
     "expr": "sum(rate(ifInBroadcastPkts{job=\"snmp_switch\", instance=\"<ROUTER_IP>\"}[5m]))",
     "legendFormat": "Broadcast"
    }
   ]
  },
  {
   "title": "Bandwidth Utilization % per Interface",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance=\"<ROUTER_IP>\", ifName=~\"Fa0/.*\"}[5m]) * 8 / ifSpeed * 100",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Interface Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 36 },
   "targets": [
    {
     "expr": "rate(ifInErrors{job=\"snmp_switch\", instance=\"<ROUTER_IP>\", ifName=~\"Fa0/([1-9]|1[0-9]|2[0-4])\"}[5m])",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Interface UP/DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{job=\"snmp_switch\", instance=\"<ROUTER_IP>\", ifName=~\"Fa0/.*\"}",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Router UpTime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"snmp_switch\", instance=\"<ROUTER_IP>\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory % Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ciscoMemoryPoolUsed{instance=\"<ROUTER_IP>\", ciscoMemoryPoolIndex=\"1\"} / (ciscoMemoryPoolUsed{ciscoMemoryPoolIndex=\"1\"} + ciscoMemoryPoolFree{ciscoMemoryPoolIndex=\"1\"}) * 100",
     "legendFormat": "Processor"
    },
    {
     "expr": "ciscoMemoryPoolUsed{instance=\"<ROUTER_IP>\", ciscoMemoryPoolIndex=\"2\"} / (ciscoMemoryPoolUsed{ciscoMemoryPoolIndex=\"2\"} + ciscoMemoryPoolFree{ciscoMemoryPoolIndex=\"2\"}) * 100",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bits/sec (bps)" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance=\"<ROUTER_IP>\", ifName=\"Fa0/0\"}[5m]) * 8",
     "legendFormat": "{{ifName}} - In"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=\"<ROUTER_IP>\", ifName=\"Fa0/0\"}[5m]) * -8",
     "legendFormat": "{{ifName}} - Out"
    }
   ]
  },
  {
   "title": "Proccesses ID CPU% (5s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, cpmProcExtUtil5SecRev{job=\"snmp-switch-cisco\", instance=\"<ROUTER_IP>\"} > 0)",
     "legendFormat": "{{cpmProcessName}} (PID: {{cpmProcessPID}})"
    }
   ]
  }
 ]
}